# Generated by Django 3.2.16 on 2023-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.CharField(default='Dinner', max_length=50),
        ),
    ]
