# Generated by Django 3.2.16 on 2023-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230127_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.CharField(choices=[('Dinner', 'Dinner')], default='Dinner', max_length=50),
        ),
    ]
