# Generated by Django 3.2.16 on 2023-01-27 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='option',
            field=models.CharField(default='Dinner', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM')], default='3 PM', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
