# Generated by Django 3.2.16 on 2023-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='option',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time_ordered',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.CharField(choices=[('Dinner', 'Dinner')], default='Dinner', max_length=50),
        ),
    ]
