# Generated by Django 3.2.16 on 2023-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20230127_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
    ]
