# Generated by Django 3.2.16 on 2023-01-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_reservation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='content',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.CharField(default='Dinner', max_length=50),
        ),
    ]
