# Generated by Django 3.2.16 on 2023-01-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20230130_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
    ]
