# Generated by Django 3.2.16 on 2023-01-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_reservation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
    ]
