# Generated by Django 3.2.16 on 2023-03-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_reservation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='content',
            new_name='comment',
        ),
    ]
