# Generated by Django 3.2.16 on 2023-03-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_rename_content_reservation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
